/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akshat (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/moon-4db2273f6dd943b8ad7fa5e3b1b2431a
title: Moon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";
import { useEffect } from "react";
export function Moon(props) {
	const moonRef = useRef();

	const { clock } = useThree();

	useEffect(() => {
		gsap.to(moonRef.current.rotation, {
			x: Math.sin(clock.elapsedTime * 0.25),
			z: Math.cos(clock.elapsedTime * 0.25),
			duration: 10,
			repeat: -1,
			yoyo: true,
		});
	});
	const { nodes, materials } = useGLTF("/moon.glb");
	return (
		<group
			ref={moonRef}
			scale={0.49}
			position={[50, 180, 800]}
			{...props}
			dispose={null}
		>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Sphere_Material002_0.geometry}
							material={materials["Material.002"]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/moon.glb");
