/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Manicartes (https://sketchfab.com/jajakronus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/road-4eae882d72c24a789d83655f952008ea
title: Road
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Road(props) {
	const roadRef = useRef();
	const { nodes, materials } = useGLTF("/road.glb");

	useFrame((state) => {
		roadRef.current.position.z =
			Math.sin(state.clock.elapsedTime * 0.3) * 200;
		roadRef.current.position.x =
			-Math.abs(Math.sin(state.clock.elapsedTime * 0.25)) * 4;
	});
	return (
		<group
			ref={roadRef}
			scale={[1000, 2, 2.5]}
			rotation-y={Math.PI / 2}
			{...props}
			dispose={null}
		>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Plane_Estrada_0.geometry}
							material={materials.Estrada}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/road.glb");
